<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NV9V8N4" failures="1" tests="12" name="testCaseBestBuy.TC_03_CreatAccountFunctionality" time="475.268" errors="1" timestamp="2025-08-30T10:17:37 IST" skipped="0">
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tearDown" time="27.068">
    <failure message="The following asserts failed:
	expected [Sorry, there was a problem creating your account.] but found [Account created successfully]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Sorry, there was a problem creating your account.] but found [Account created successfully]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at baseBestBuy.BaseClassBB.tearDown(BaseClassBB.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:836)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:805)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:781)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- tearDown -->
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="43.908"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="43.057"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="43.364"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="51.719">
    <error message="See extent report for more details" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: See extent report for more details
at baseBestBuy.BaseClassBB.reportStep(BaseClassBB.java:311)
at testCaseBestBuy.TC_03_CreatAccountFunctionality.tc_03_validateCreatAccountFunctionality(TC_03_CreatAccountFunctionality.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- tc_03_validateCreatAccountFunctionality -->
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="41.595"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="40.103"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="42.611"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="41.845"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="42.547"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="42.714"/>
  <testcase classname="testCaseBestBuy.TC_03_CreatAccountFunctionality" name="tc_03_validateCreatAccountFunctionality" time="14.737"/>
</testsuite> <!-- testCaseBestBuy.TC_03_CreatAccountFunctionality -->
